services:
  postgres:
    image: postgres:16-alpine
    container_name: easypet-postgres
    environment:
      POSTGRES_DB: easypet_db
      POSTGRES_USER: easypet_user
      POSTGRES_PASSWORD: easypet_pass
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U easypet_user -d easypet_db']
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: easypet-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: